using System.Collections.Generic;

namespace RPGGame
{
    public enum Language { Chinese = 0, English = 1, Japanese = 2 }

    public static class L10n
    {
        public static Language Current { get; set; } = Language.Chinese;
        private static int I => (int)Current;

        public static string Get(string key, params object[] args)
        {
            if (!S.TryGetValue(key, out var arr)) return key;
            string raw = I < arr.Length ? arr[I] : arr[0];
            return args.Length > 0 ? string.Format(raw, args) : raw;
        }

        private static readonly Dictionary<string, string[]> S = new()
        {
            // ── Language Selection ─────────────────────────────────────────
            ["LANG_TITLE"]          = ["  語言選擇 / Language / 言語選択", "  語言選擇 / Language / 言語選択", "  語言選擇 / Language / 言語選択"],
            ["LANG_ZH"]             = ["  [1] 繁體中文", "  [1] Traditional Chinese", "  [1] 繁体中文"],
            ["LANG_EN"]             = ["  [2] English", "  [2] English", "  [2] English"],
            ["LANG_JA"]             = ["  [3] 日本語", "  [3] Japanese", "  [3] 日本語"],
            ["LANG_PROMPT"]         = ["選擇", "Select", "選択"],

            // ── Class Names ────────────────────────────────────────────────
            ["CLASS_WARRIOR"]       = ["戰士", "Warrior", "戦士"],
            ["CLASS_MAGE"]          = ["法師", "Mage", "魔法使い"],
            ["CLASS_ASSASSIN"]      = ["刺客", "Assassin", "暗殺者"],
            ["CLASS_HERO"]          = ["勇者", "Hero", "勇者"],

            // ── Main Menu ─────────────────────────────────────────────────
            ["MENU_TITLE"]          = ["【主 選 單】", "[ MAIN  MENU ]", "【メインメニュー】"],
            ["MENU_NEW_GAME"]       = ["  [1] 新遊戲", "  [1] New Game", "  [1] ニューゲーム"],
            ["MENU_LOAD"]           = ["  [2] 讀取存檔", "  [2] Load Game", "  [2] データロード"],
            ["MENU_LOAD_NONE"]      = ["  [2] 讀取存檔（無存檔）", "  [2] Load Game (no save)", "  [2] データロード（データなし）"],
            ["MENU_HELP"]           = ["  [3] 遊玩說明", "  [3] How to Play", "  [3] ヘルプ"],
            ["MENU_QUIT"]           = ["  [4] 退出遊戲", "  [4] Quit", "  [4] 終了"],
            ["MENU_SELECT"]         = ["選擇", "Select", "選択"],

            // ── Character Creation ─────────────────────────────────────────
            ["CREATE_TITLE"]        = ["創 建 角 色", "CHARACTER  CREATION", "キャラクター作成"],
            ["CREATE_WELCOME_1"]    = ["  歡迎來到《暴走：黑暗年代記》", "  Welcome to RAGE: Chronicles of Darkness", "  「暴走：黑暗年代記」へようこそ"],
            ["CREATE_WELCOME_2"]    = ["  這是一個關於憤怒、選擇與自我的故事。", "  A story of rage, choice, and the self.", "  怒り、選択、そして自己についての物語。"],
            ["CREATE_NAME_PROMPT"]  = ["請輸入角色名字", "Enter your character name", "キャラクター名を入力"],
            ["CREATE_DEFAULT_NAME"] = ["勇者", "Hero", "勇者"],
            ["CREATE_CLASS_INTRO"]  = ["\n  選擇你的職業：", "\n  Choose your class:", "\n  クラスを選択："],
            ["CREATE_CLASS_1"]      = ["  [1] 戰士  ── HP+30, DEF+5，怒氣累積較快", "  [1] Warrior  ── HP+30, DEF+5, faster rage buildup", "  [1] 戦士  ── HP+30、DEF+5、怒気蓄積速い"],
            ["CREATE_CLASS_2"]      = ["  [2] 法師  ── MP+30, ATK+3，技能傷害提升", "  [2] Mage     ── MP+30, ATK+3, higher skill damage", "  [2] 魔法使い ── MP+30、ATK+3、スキルダメージ増加"],
            ["CREATE_CLASS_3"]      = ["  [3] 刺客  ── ATK+8，每次攻擊獲得更多怒氣", "  [3] Assassin ── ATK+8, more rage per attack", "  [3] 暗殺者  ── ATK+8、攻撃ごとに怒気増加"],
            ["CREATE_CLASS_SELECT"] = ["選擇職業", "Choose class", "クラスを選択"],
            ["INTRO_WARRIOR"]       = ["是一名無畏的戰士", "is a fearless warrior", "は無敵の戦士"],
            ["INTRO_MAGE"]          = ["是一名精通魔法的法師", "is a master of the arcane arts", "は魔法の達人"],
            ["INTRO_ASSASSIN"]      = ["是一名行動敏捷的刺客", "is a swift and deadly assassin", "は素早い暗殺者"],

            // ── Battle UI ─────────────────────────────────────────────────
            ["BATTLE_ACTION_TITLE"] = ["  【行動選擇】", "  [ ACTION ]", "  【行動選択】"],
            ["BATTLE_ACTION_1"]     = ["  [1] 普通攻擊", "  [1] Attack", "  [1] 通常攻撃"],
            ["BATTLE_ACTION_2"]     = ["  [2] 使用技能", "  [2] Use Skill", "  [2] スキル使用"],
            ["BATTLE_ACTION_3"]     = ["  [3] 防禦姿態（受到傷害減半）", "  [3] Defend (halve damage taken)", "  [3] 防御態勢（被ダメ半減）"],
            ["BATTLE_ACTION_4"]     = ["  [4] 查看狀態", "  [4] View Status", "  [4] ステータス確認"],
            ["BATTLE_ACTION_SELECT"]= ["選擇行動", "Choose action", "行動を選択"],
            ["BATTLE_SKILL_TITLE"]  = ["  【技能列表】", "  [ SKILLS ]", "  【スキル一覧】"],
            ["BATTLE_SKILL_BACK"]   = ["  [0] 返回", "  [0] Back", "  [0] 戻る"],
            ["BATTLE_SKILL_SELECT"] = ["選擇技能", "Choose skill", "スキルを選択"],
            ["BATTLE_MP_LOW"]       = ["  ✗ MP 不足！", "  ✗ Not enough MP!", "  ✗ MPが足りない！"],
            ["BATTLE_RAGE_LOW"]     = ["  ✗ 怒氣不足！", "  ✗ Not enough rage!", "  ✗ 怒気が足りない！"],
            ["BATTLE_START"]        = ["[ 按任意鍵開始戰鬥... ]", "[ Press any key to start battle... ]", "[ 何かキーを押して戦闘開始... ]"],

            // ── Battle Messages ────────────────────────────────────────────
            ["BATTLE_STUN_PLAYER"]  = ["  {0} 眩暈中，無法行動！", "  {0} is stunned and cannot act!", "  {0}は眩暈で行動できない！"],
            ["BATTLE_BACKFIRE"]     = ["  ★ 暴走失控！{0} 反噬自身 {1} 點！(HP: {2}/{3})", "  ★ Lost control! {0} takes {1} backfire damage! (HP: {2}/{3})", "  ★ 制御不能！{0}が{1}ダメージを自傷！(HP: {2}/{3})"],
            ["BATTLE_ATTACK_HIT"]   = ["  {0}{1} 攻擊 {2} → 造成 {3} 點傷害！", "  {0}{1} attacks {2} → deals {3} damage!", "  {0}{1}が{2}を攻撃 → {3}ダメージ！"],
            ["BATTLE_BERSERK_TAG"]  = [" ★暴走★", " ★BERSERK★", " ★暴走★"],
            ["BATTLE_SKILL_USE"]    = ["  ✦ {0} 使用了【{1}】！", "  ✦ {0} used [{1}]!", "  ✦ {0}が【{1}】を使用した！"],
            ["BATTLE_HEAL_MSG"]     = ["  ♥ 恢復了 {0} 點 HP！(HP: {1}/{2})", "  ♥ Restored {0} HP! (HP: {1}/{2})", "  ♥ HP{0}回復！(HP: {1}/{2})"],
            ["BATTLE_RAGE_SKILL_BACKFIRE"] = ["  ★ 力量失控！{0} 反噬 {1} 點！", "  ★ Power out of control! {0} takes {1} self-damage!", "  ★ 力が暴走！{0}が{1}の自傷ダメージ！"],
            ["BATTLE_SKILL_HIT"]    = ["  → 對 {0} 造成 {1} 點傷害！", "  → Dealt {1} damage to {0}!", "  → {0}に{1}ダメージ！"],
            ["BATTLE_BURN_APPLY"]   = ["  🔥 {0} 陷入燃燒狀態！(每回合 9 點)", "  🔥 {0} is burning! (9 damage/turn)", "  🔥 {0}が燃焼状態に！（毎ターン9ダメージ）"],
            ["BATTLE_STUN_APPLY"]   = ["  ⚡ {0} 被眩暈了！下回合無法行動！", "  ⚡ {0} is stunned! Cannot act next turn!", "  ⚡ {0}が眩暈状態に！次ターン行動不能！"],
            ["BATTLE_CRIT_APPLY"]   = ["  ★★ 追加暴擊！額外 {0} 點傷害！", "  ★★ Critical hit! Extra {0} damage!", "  ★★ 追加クリティカル！{0}の追加ダメージ！"],
            ["BATTLE_DEFEND"]       = ["  🛡 {0} 進入防禦姿態！本回合受到傷害減半。", "  🛡 {0} takes a defensive stance! Damage halved.", "  🛡 {0}が防御態勢に！このターンの被ダメージ半減。"],
            ["BATTLE_DEFEND_TAG"]   = ["  🛡 防禦！", "  🛡 Defended!", "  🛡 防御！"],
            ["BATTLE_ENEMY_STUN"]   = ["  {0} 眩暈中，無法行動！", "  {0} is stunned and cannot act!", "  {0}は眩暈で行動できない！"],
            ["BATTLE_ENEMY_ATTACK"] = ["  {0} 攻擊 {1} → 受到 {2} 點傷害！(HP: {3}/{4})", "  {0} attacks {1} → takes {2} damage! (HP: {3}/{4})", "  {0}が{1}を攻撃 → {2}ダメージ！(HP: {3}/{4})"],
            ["BATTLE_ENEMY_SPECIAL"]= ["  ☠ {0} 使用【{1}】！→ {2} 受到 {3} 點傷害！(HP: {4}/{5})", "  ☠ {0} uses [{1}]! → {2} takes {3} damage! (HP: {4}/{5})", "  ☠ {0}が【{1}】を使用！→ {2}が{3}ダメージ！(HP: {4}/{5})"],
            ["BATTLE_BURN_PLAYER"]  = ["  {0} 受到灼燒傷害 {1}！(HP: {2}/{3})", "  {0} takes {1} burn damage! (HP: {2}/{3})", "  {0}が{1}の灼熱ダメージ！(HP: {2}/{3})"],
            ["BATTLE_BURN_ENEMY"]   = ["  {0} 受到灼燒傷害 {1}！(HP: {2}/{3})", "  {0} takes {1} burn damage! (HP: {2}/{3})", "  {0}が{1}の灼熱ダメージ！(HP: {2}/{3})"],
            ["BATTLE_BURN_KILL"]    = ["  燃燒使其倒下了！", "  Burned to the ground!", "  燃焼でやられた！"],
            ["BATTLE_EXP_GAIN"]     = ["  ▶ 獲得 {0} EXP！", "  ▶ Gained {0} EXP!", "  ▶ {0}EXP獲得！"],
            ["BATTLE_LEVEL_UP"]     = ["  ★★ 升級！{0} 達到 Lv.{1}！", "  ★★ Level up! {0} reached Lv.{1}!", "  ★★ レベルアップ！{0}がLv.{1}に！"],
            ["BATTLE_LEVEL_STATS"]  = ["     HP+20 / MP+10 / ATK+3 / DEF+2", "     HP+20 / MP+10 / ATK+3 / DEF+2", "     HP+20 / MP+10 / ATK+3 / DEF+2"],
            ["BATTLE_MP_RESTORE"]   = ["  ▶ 戰鬥後恢復 15 MP", "  ▶ Restored 15 MP after battle", "  ▶ 戦闘後MP15回復"],
            ["BATTLE_DEFEAT_MSG"]   = ["  {0} 倒下了...", "  {0} has fallen...", "  {0}が倒れた…"],
            ["SKILL_UNLOCK"]        = ["  ✦ 解鎖新技能：【{0}】【{1}】！", "  ✦ New skills unlocked: [{0}] [{1}]!", "  ✦ 新スキル解放：【{0}】【{1}】！"],

            // ── Berserk Messages ───────────────────────────────────────────
            ["BERSERK_TRIGGER_1"]   = ["  ★★★ {0} 的怒氣徹底爆發！！！", "  ★★★ {0}'s rage erupts completely!!!", "  ★★★ {0}の怒りが爆発した！！！"],
            ["BERSERK_TRIGGER_2"]   = ["  ★★★ 進入【暴走狀態】！攻擊力大幅提升，但可能失控！★★★", "  ★★★ Enters [BERSERK STATE]! ATK greatly increased, but may lose control! ★★★", "  ★★★【暴走状態】に突入！ATK大幅上昇、しかし制御不能になる危険も！★★★"],
            ["BERSERK_END"]         = ["  {0} 從暴走狀態中逐漸清醒...", "  {0} is coming down from berserk...", "  {0}が暴走状態から覚めていく…"],

            // ── Status Display Labels ──────────────────────────────────────
            ["STATUS_BERSERK_TAG"]  = ["★暴走", "★BERSERK", "★暴走"],
            ["STATUS_DEFENDING"]    = ["[防禦姿態]", "[Defending]", "[防御態勢]"],
            ["STATUS_RAGE"]         = ["怒 ", "RAGE", "怒気"],
            ["STATUS_RAGE_MAX"]     = ["MAX", "MAX", "MAX"],

            // ── Equipment ──────────────────────────────────────────────────
            ["EQUIP_WEAPON_MSG"]    = ["  ✦ 裝備武器：{0}（ATK +{1}）", "  ✦ Equipped: {0} (ATK +{1})", "  ✦ 武器装備：{0}（ATK+{1}）"],
            ["EQUIP_ARMOR_MSG"]     = ["  ✦ 裝備防具：{0}（DEF +{1}）", "  ✦ Equipped: {0} (DEF +{1})", "  ✦ 防具装備：{0}（DEF+{1}）"],
            ["EQUIP_DARK_STONE"]    = ["黑暗符石強化", "Dark Rune Augment", "暗黒符石強化"],
            ["EQUIP_FOREST_ARMOR"]  = ["林中鐵甲", "Forest Iron Armor", "森の鉄鎧"],
            ["EQUIP_DARK_BLADE"]    = ["黑暗聖劍", "Dark Holy Blade", "暗黒聖剣"],
            ["EQUIP_HOLY_BLADE"]    = ["淨化聖劍", "Purified Holy Blade", "浄化聖剣"],

            // ── Skill Names & Descriptions ─────────────────────────────────
            ["SKILL_FIREBALL_NAME"] = ["火球術", "Fireball", "火球術"],
            ["SKILL_FIREBALL_DESC"] = ["召喚火焰轟炸，有機率使敵人燃燒", "Summon a fiery blast, chance to ignite the enemy", "炎の爆発を呼び起こす、敵を燃焼させる確率あり"],
            ["SKILL_HEAL_NAME"]     = ["治癒術", "Heal", "治癒術"],
            ["SKILL_HEAL_DESC"]     = ["消耗 MP 恢復自身 HP", "Consume MP to restore your HP", "MPを消費してHPを回復"],
            ["SKILL_SHIELD_NAME"]   = ["盾擊", "Shield Bash", "シールドバッシュ"],
            ["SKILL_SHIELD_DESC"]   = ["近身衝撞，有機率使敵人眩暈", "A close-range slam with a chance to stun", "近距離の衝撃、敵を眩暈させる確率あり"],
            ["SKILL_BERSERK_NAME"]  = ["暴走衝擊", "Berserk Smash", "暴走スマッシュ"],
            ["SKILL_BERSERK_DESC"]  = ["消耗 40 怒氣，釋放毀滅性打擊，高機率暴擊", "Spend 40 rage for a devastating blow with high crit chance", "怒気40消費、壊滅的な一撃、高い暴擊率"],
            ["SKILL_ICE_NAME"]      = ["冰霜新星", "Ice Nova", "アイスノヴァ"],
            ["SKILL_ICE_DESC"]      = ["大範圍冰霜衝擊，必定眩暈敵人", "Wide-range frost blast, guaranteed stun", "広範囲の氷撃、必ず眩暈を与える"],
            ["SKILL_GREATHEAL_NAME"]= ["大治癒術", "Greater Heal", "大治癒術"],
            ["SKILL_GREATHEAL_DESC"]= ["強力治癒魔法，大量恢復 HP", "Powerful healing magic, restores a large amount of HP", "強力な治癒魔法、大量のHP回復"],

            // ── Chapter Titles ─────────────────────────────────────────────
            ["CH1_TITLE"]           = ["第一章  覺醒", "Chapter 1  Awakening", "第一章  覚醒"],
            ["CH2_TITLE"]           = ["第二章  暗黑森林", "Chapter 2  The Dark Forest", "第二章  暗黒の森"],
            ["CH3_TITLE"]           = ["第三章  魔王城", "Chapter 3  The Demon Fortress", "第三章  魔王城"],
            ["FINAL_BATTLE"]        = ["最 終 決 戰", "FINAL  BATTLE", "最 終 決 戦"],

            // ── Story Choices ───────────────────────────────────────────────
            ["CHOICE_TITLE"]        = ["抉 擇", "C H O I C E", "選 択"],
            ["FINAL_CHOICE_TITLE"]  = ["最終抉擇", "FINAL CHOICE", "最終選択"],
            ["YOUR_CHOICE"]         = ["你的選擇", "Your choice", "あなたの選択"],
            ["CH1_CHOICE_1"]        = ["  [1] 立刻出手相救（消耗 15 MP）", "  [1] Rush to help her (costs 15 MP)", "  [1] すぐに助ける（MP15消費）"],
            ["CH1_CHOICE_2"]        = ["  [2] 趕路要緊，先別節外生枝", "  [2] Press on — no time for detours", "  [2] 急ぐ、寄り道している場合ではない"],
            ["CH2_CHOICE_1"]        = ["  [1] 吸收符石的力量（ATK +6，腐化值大幅上升）", "  [1] Absorb the rune's power (ATK +6, high corruption)", "  [1] 符石の力を吸収（ATK+6、腐敗値大幅上昇）"],
            ["CH2_CHOICE_2"]        = ["  [2] 砸碎符石，拒絕黑暗誘惑", "  [2] Smash the rune, refuse the darkness", "  [2] 符石を砕き、闇の誘惑を拒む"],
            ["CH3_CHOICE_1"]        = ["  [1] 「無論如何，我必須終結這一切！」（勇者之路）", "  [1] \"No matter what — I will end this!\" (Hero's Path)", "  [1] 「何があっても、終わらせる！」（勇者の道）"],
            ["CH3_CHOICE_2"]        = ["  [2] 「...我想聽你說完。」（接受魔王的交易）", "  [2] \"...I want to hear you out.\" (Make a deal)", "  [2] 「……最後まで聞かせてくれ。」（魔王との取引）"],

            // ── Chapter 1 Story ─────────────────────────────────────────────
            ["CH1_01"]  = ["  黑暗中，一雙眼睛緩緩睜開。",
                           "  In the darkness, a pair of eyes slowly opened.",
                           "  暗闇の中、ゆっくりと瞼が開く。"],
            ["CH1_02"]  = ["  你是 {0}，一名被世界遺忘的{1}。",
                           "  You are {0}, a {1} forgotten by the world.",
                           "  お前は{0}——世界に忘れ去られた{1}。"],
            ["CH1_AWAKEN_WARRIOR"]  = ["  雙手本能地握緊——身體還記得劍的重量。",
                                       "  Your hands clench instinctively — your body still remembers the sword.",
                                       "  手が本能的に握り締まる——体はまだ剣の重みを覚えている。"],
            ["CH1_AWAKEN_MAGE"]     = ["  魔力在指尖微微流動，三年沉眠未能將它熄滅。",
                                       "  Mana stirs faintly at your fingertips — three years of sleep couldn't extinguish it.",
                                       "  魔力が指先でかすかに流れる——三年の眠りもそれを消せなかった。"],
            ["CH1_AWAKEN_ASSASSIN"] = ["  眼睛在黑暗中快速適應，習慣性地掃描每個角落。",
                                       "  Your eyes adapt to the darkness instantly, scanning every corner by instinct.",
                                       "  目が素早く闇に慣れ、本能的に隅々を見渡す。"],
            ["CH1_03"]  = ["  三年前，魔王夜陌魯斯率領魔族大軍入侵，",
                           "  Three years ago, the Demon King Yamatolusu led his forces to invade,",
                           "  三年前、魔王・夜陌魯斯が魔族の大軍を率いて侵攻し、"],
            ["CH1_04"]  = ["  你在最後的戰役中受了致命重傷，此後一直昏迷。",
                           "  and you fell in the final battle with fatal wounds, unconscious ever since.",
                           "  お前は最後の戦いで致命傷を負い、それ以来ずっと昏睡状態だった。"],
            ["CH1_05"]  = ["  「你... 終於醒了。」",
                           "  \"You... have finally awakened.\"",
                           "  「お前が……ついに目覚めたか。」"],
            ["CH1_06"]  = ["  一個蒼老的聲音從陰暗角落傳來——是村裡的老祭司。",
                           "  An aged voice comes from a shadowed corner — the village elder priest.",
                           "  老いた声が薄暗い隅から聞こえる——村の老祭司だ。"],
            ["CH1_07"]  = ["  「魔王的軍隊三天後就會到達這個村子。」",
                           "  \"The Demon King's army will reach this village in three days.\"",
                           "  「魔王の軍勢が3日後にこの村へ来る。」"],
            ["CH1_08"]  = ["  「你... 是我們最後的希望。」",
                           "  \"You... are our last hope.\"",
                           "  「お前が……我々の最後の希望だ。」"],
            ["CH1_09"]  = ["  踏出村子的那一刻，一隻史萊姆從草叢中彈了出來。",
                           "  The moment you stepped out of the village, a slime burst from the undergrowth.",
                           "  村を出た瞬間、草むらからスライムが飛び出してきた。"],
            ["CH1_10"]  = ["  「好吧，先熱身一下。」你低聲說，握緊武器。",
                           "  \"Alright, a warm-up then,\" you murmur, tightening your grip.",
                           "  「なるほど、まず準備運動といこう。」お前は低くつぶやき、武器を握り締めた。"],
            ["CH1_11"]  = ["  繼續前進時，你聽到一陣哭喊聲。",
                           "  As you press forward, you hear desperate cries.",
                           "  前進する中、叫び声が聞こえてきた。"],
            ["CH1_12"]  = ["  一名老婆婆被兩隻哥布林追趕，情況危急。",
                           "  An elderly woman is being chased by two goblins — the situation is dire.",
                           "  老婆が2匹のゴブリンに追われていた——切迫した状況だ。"],
            ["CH1_13"]  = ["  哥布林手中還拿著一塊散發微光的石板。",
                           "  The goblins clutch a stone tablet that glows with a faint, eerie light.",
                           "  ゴブリンたちは微かに光る石板を掴んでいた。"],
            ["CH1_HELP_1"] = ["  你衝上前，一道魔法擊退了哥布林。",
                              "  You rush forward and blast the goblins away.",
                              "  お前は駆け出し、力でゴブリンたちを吹き飛ばした。"],
            ["CH1_HELP_2"] = ["  老婆婆顫抖著站起身，淚流滿面地看著你：",
                              "  The old woman shakily gets to her feet, tears streaming down her face:",
                              "  老婆は震えながら立ち上がり、涙を流してお前を見上げた："],
            ["CH1_HELP_3"] = ["  「謝謝你，孩子。我的孫子還在城裡...」",
                              "  \"Thank you, child. My grandchild is still in the city...\"",
                              "  「ありがとう、坊や。孫がまだ城にいるんだよ……」"],
            ["CH1_HELP_4"] = ["  「請你一定要打倒魔王，救救他們。」",
                              "  \"Please — you must defeat the Demon King. Save them.\"",
                              "  「どうか魔王を倒して、みんなを救っておくれ。」"],
            ["CH1_HELP_BONUS"] = ["  ✦ 獲得老婆婆的祝福（最大 HP +15）",
                                   "  ✦ Received the old woman's blessing (Max HP +15)",
                                   "  ✦ 老婆の祝福を受けた（最大HP+15）"],
            ["CH1_SKIP_1"] = ["  你咬牙轉過身，加快腳步。",
                              "  You grit your teeth, turn away, and quicken your pace.",
                              "  お前は歯を食いしばり、背を向けて足を速めた。"],
            ["CH1_SKIP_2"] = ["  老婆婆的呼救聲漸漸在身後消散。",
                              "  The old woman's cries fade behind you.",
                              "  老婆の叫び声が背後で遠ざかっていく。"],
            ["CH1_SKIP_3"] = ["  「對不起...」你心底一陣刺痛，但腳步沒有停下。",
                              "  \"I'm sorry...\" A sharp ache pierces your heart, but your feet don't stop.",
                              "  「すまない……」胸に痛みが走ったが、足は止まらなかった。"],

            // ── Chapter 2 Story ─────────────────────────────────────────────
            ["CH2_01"]  = ["  踏入暗黑森林，濃稠的黑氣如同活物般纏繞四周。",
                           "  You step into the Dark Forest. A thick black miasma coils around you like something alive.",
                           "  暗黒の森に踏み込む。濃い黒霧が生き物のように周囲に絡みついてくる。"],
            ["CH2_02"]  = ["  樹木扭曲成奇異的形狀，彷彿在無聲地哀嚎。",
                           "  The trees are twisted into grotesque shapes, as if silently crying out.",
                           "  木々が奇妙な形に歪み、まるで声のない悲鳴を上げているかのようだ。"],
            ["CH2_03"]  = ["  「這裡的一切都被魔王的力量腐化了...」你心想。",
                           "  \"Everything here has been corrupted by the Demon King's power...\" you think.",
                           "  「ここにあるものすべてが、魔王の力に腐食されている……」お前は思った。"],
            ["CH2_04"]  = ["  一個身著黑鐵盔甲的哥布林騎士擋住了去路，",
                           "  A goblin knight clad in black iron armor blocks your path.",
                           "  黒鉄の鎧を纏ったゴブリン騎士が行く手を遮った。"],
            ["CH2_05"]  = ["  「死在這裡吧，人類！」牠嘶吼著，舉起毒矛。",
                           "  \"Die here, human!\" it snarls, raising a venomous spear.",
                           "  「ここで死ね、人間！」奴は吠えながら毒槍を振り上げた。"],
            ["CH2_DARK_1"] = ["  從哥布林騎士的遺骸中，你發現了一塊漆黑的符石。",
                              "  From the goblin knight's remains, you find a pitch-black rune.",
                              "  ゴブリン騎士の遺骸から、漆黒の符石を発見した。"],
            ["CH2_DARK_2"] = ["  它在你手中顫動，散發著既危險又誘人的黑暗力量。",
                              "  It trembles in your hand, radiating a power that is both dangerous and seductive.",
                              "  それは手の中で震え、危険でありながら誘惑的な闇の力を放っている。"],
            ["CH2_ABSORB_1"] = ["  黑暗能量衝入你的全身，你感到無比強大。",
                                "  Dark energy floods through you — you feel overwhelmingly powerful.",
                                "  暗黒のエネルギーが全身を駆け巡る——無限の力を感じた。"],
            ["CH2_ABSORB_2"] = ["  但心中某個純粹的東西，似乎在這一刻悄然消逝了。",
                                "  But something pure inside you seems to quietly vanish in this moment.",
                                "  しかし、心の中の純粋な何かがこの瞬間、静かに消えていったようだった。"],
            ["CH2_ABSORB_BONUS"] = ["  ✦ ATK +6，但腐化值大幅上升",
                                    "  ✦ ATK +6, but corruption greatly increased",
                                    "  ✦ ATK+6、しかし腐敗値が大幅上昇"],
            ["CH2_SMASH_1"] = ["  你用力將符石砸在地上，黑暗能量四散消逝。",
                               "  You slam the rune to the ground. The dark energy scatters and fades.",
                               "  お前は符石を地面に叩き付けた。暗黒のエネルギーが四散し、消えていった。"],
            ["CH2_SMASH_2"] = ["  「我不需要這種東西。」你低聲說，聲音十分堅定。",
                               "  \"I don't need this,\" you say quietly, your voice firm.",
                               "  「こんなものはいらない。」お前は静かに、しかし確固として言った。"],
            ["CH2_WRAITH_1"] = ["  深入森林，一個漆黑的靈體從陰影中浮現。",
                                "  Deep in the forest, a pitch-black wraith emerges from the shadows.",
                                "  森の奥深く、漆黒の霊体が影から現れた。"],
            ["CH2_WRAITH_2"] = ["  「你以為能打倒魔王？」幽靈冰冷地低語，",
                                "  \"You think you can defeat the Demon King?\" the wraith whispers coldly,",
                                "  「魔王を倒せると思っているのか？」霊体は冷たく囁く、"],
            ["CH2_WRAITH_3"] = ["  「就連你的憤怒與痛苦，都是他的力量之源。」",
                                "  \"Your very rage and suffering are the source of his power.\"",
                                "  「お前の怒りと苦しみこそが、あの方の力の源なのだ。」"],
            ["CH2_AFTER_1"] = ["  靈體消散後，你感到胸腔中有什麼東西在沸騰。",
                               "  After the wraith dissolves, you feel something boiling inside your chest.",
                               "  霊体が消えた後、胸の中で何かが沸騰しているように感じた。"],
            ["CH2_AFTER_2"] = ["  每一次攻擊、每一次受傷，都讓那股熱流更加洶湧。",
                               "  Every attack, every wound — each one feeds that burning surge.",
                               "  攻撃するたびに、傷つくたびに、その熱い流れは激しくなっていく。"],
            ["CH2_BERSERK_HINT_1"] = ["  你已經嘗過那種失控的感覺——那股暴走之力。",
                                      "  You've already felt it — that wild, uncontrollable power.",
                                      "  お前はすでにあの感覚を知っている——あの暴走する力を。"],
            ["CH2_BERSERK_HINT_2"] = ["  「它... 真的能被我掌控嗎？」你不確定地問自己。",
                                      "  \"Can I really control it?\" you wonder, uncertain.",
                                      "  「本当に制御できるのか？」お前は自問した、確信なく。"],
            ["CH2_RAGE_1"] = ["  「這股力量...是憤怒？還是別的什麼？」你自問。",
                              "  \"This power... is it rage? Or something else entirely?\" you wonder.",
                              "  「この力は……怒りなのか？それとも別の何かなのか？」お前は自問した。"],

            // ── Chapter 3 Story ─────────────────────────────────────────────
            ["CH3_01"]  = ["  魔王城就在眼前，黑色的尖塔刺穿陰雲密布的天空。",
                           "  The Demon Fortress stands before you, black spires piercing the overcast sky.",
                           "  魔王城が目の前にそびえ立つ。黒い尖塔が曇り空を突き刺している。"],
            ["CH3_02"]  = ["  城門大開，彷彿在靜靜等待著你的到來。",
                           "  The gates stand open, as if quietly waiting for your arrival.",
                           "  城門は開け放たれ、まるでお前の訪れを静かに待っているかのようだ。"],
            ["CH3_03"]  = ["  城門前，一名身著精緻黑甲的騎士緩緩轉身。",
                           "  Before the gates, a knight clad in ornate black armor slowly turns to face you.",
                           "  城門の前、精緻な黒鎧を纏った騎士がゆっくりと振り向く。"],
            ["CH3_04"]  = ["  「我曾是這個王國最偉大的聖騎士。」",
                           "  \"I was once this kingdom's greatest holy knight.\"",
                           "  「かつて私はこの王国で最も偉大な聖騎士だった。」"],
            ["CH3_05"]  = ["  「如今...我是魔王手中最鋒利的劍。」",
                           "  \"Now... I am the sharpest blade in the Demon King's hand.\"",
                           "  「今は……魔王の手の中の、最も鋭い剣だ。」"],
            ["CH3_PALADIN_1"] = ["  黑甲從騎士身上碎裂，黑暗能量緩緩消散。",
                                 "  The black armor shatters from the knight's body. Dark energy slowly disperses.",
                                 "  黒鎧が騎士の体から砕け散り、暗黒のエネルギーがゆっくりと消えていく。"],
            ["CH3_PALADIN_2"] = ["  倒在地上的騎士喃喃道：",
                                 "  The knight, fallen to the ground, murmurs:",
                                 "  地に倒れた騎士は呟く："],
            ["CH3_PALADIN_3"] = ["  「謝... 謝謝你... 終於... 解脫了...」",
                                 "  \"Th... thank you... finally... free...\"",
                                 "  「あり……ありがとう……ようやく……解放された……」"],
            ["CH3_PALADIN_4"] = ["  他閉上眼睛，臉上浮現出多年未有的平靜神情。",
                                 "  He closes his eyes. A peace he hasn't known in years settles across his face.",
                                 "  彼は目を閉じた。長年なかった安らぎの表情が顔に浮かんだ。"],
            ["CH3_EQUIP_DARK"]  = ["  ✦ 黑暗能量注入聖劍，你感覺它在呼應你體內的腐化。",
                                   "  ✦ Dark energy flows into the holy blade, resonating with the corruption within you.",
                                   "  ✦ 暗黒のエネルギーが聖剣に宿り、体内の腐敗と共鳴しているのを感じる。"],
            ["CH3_EQUIP_HOLY"]  = ["  ✦ 聖劍的力量在你手中閃耀，彷彿認可了你的意志。",
                                   "  ✦ The holy blade gleams in your hand, as if acknowledging your resolve.",
                                   "  ✦ 聖剣の力がお前の手の中で輝き、まるでお前の意志を認めるかのようだ。"],
            ["CH3_DEMON_1"] = ["  進入魔王城深處，黑暗的聲音在牆壁間迴盪：",
                               "  Deep inside the fortress, a voice of darkness echoes between the walls:",
                               "  魔王城の奥深くに入ると、闇の声が壁の間にこだまする："],
            ["CH3_DEMON_2"] = ["  「勇者，你終於來了。我等你等了很久。」",
                               "  \"Hero — you've finally come. I've been waiting a long time.\"",
                               "  「勇者よ、ようやく来たか。ずっと待っていたぞ。」"],
            ["CH3_DEMON_3"] = ["  「你知道嗎？你體內那股暴走之力，」",
                               "  \"Do you know? That berserk power inside you —\"",
                               "  「知っているか？お前の中にある暴走の力——」"],
            ["CH3_DEMON_4"] = ["  「與我的魔力，其實來自同一個源頭——純粹的憤怒。」",
                               "  \"— and my demon power, they come from the same source: pure rage.\"",
                               "  「——と私の魔力は、実は同じ源から来ている——純粋な怒りだ。」"],
            ["CH3_DEAL_1"] = ["  魔王低笑：「明智。那麼，讓我給你真正的力量。」",
                              "  The Demon King chuckles: \"Wise. Then let me give you real power.\"",
                              "  魔王は低く笑う：「賢明だ。では、本物の力を与えよう。」"],
            ["CH3_DEAL_2"] = ["  一股滔天的黑暗能量湧入你的身體。",
                              "  A massive surge of dark energy floods into your body.",
                              "  圧倒的な暗黒のエネルギーが体に流れ込んでくる。"],
            ["CH3_DEAL_3"] = ["  你感到前所未有的強大——以及前所未有的空洞。",
                              "  You feel an unprecedented power — and an unprecedented emptiness.",
                              "  かつてない強さを感じた——そして、かつてない空虚さも。"],
            ["CH3_DEAL_BONUS"] = ["  ✦ 所有屬性大幅提升，但腐化值已達警戒線",
                                   "  ✦ All stats greatly increased, but corruption is at critical level",
                                   "  ✦ 全ステータス大幅上昇、しかし腐敗値が警戒ラインに達した"],
            ["CH3_FIGHT_1"] = ["  「我不需要了解你！」",
                               "  \"I don't need to understand you!\"",
                               "  「お前のことなど知る必要はない！」"],
            ["CH3_FIGHT_2"] = ["  你怒吼著，衝向黑暗的深處！",
                               "  You roar and charge headlong into the darkness!",
                               "  お前は怒鳴り声を上げ、闇の奥へと突進した！"],

            // ── Ending: Good (Light) ────────────────────────────────────────
            ["END_GOOD_TITLE"]   = ["好結局：光明的彼岸", "Good Ending: Dawn of Light", "グッドエンド：光の彼方"],
            ["END_GOOD_01"]  = ["  魔王夜陌魯斯轟然倒地，黑暗之力從世界各角落消散。",
                                "  Demon King Yamatolusu crashes to the ground. Darkness recedes from every corner of the world.",
                                "  魔王・夜陌魯斯が倒れ込む。闇の力が世界の隅々から消えていく。"],
            ["END_GOOD_02"]  = ["  天空緩緩破曉，久違的陽光穿透雲層，照亮大地。",
                                "  The sky slowly brightens. Sunlight, long absent, breaks through the clouds.",
                                "  空がゆっくりと明け始め、久しぶりの陽光が雲を突き破り、大地を照らす。"],
            ["END_GOOD_03"]  = ["  {0} 佇立在魔王城的廢墟上，",
                                "  {0} stands in the ruins of the Demon Fortress,",
                                "  {0}は魔王城の廃墟に立ち、"],
            ["END_GOOD_04"]  = ["  三年的昏迷，三天的旅程，此刻都化為胸中的平靜。",
                                "  three years of coma, three days of journey — all dissolved into a deep calm.",
                                "  三年の昏睡、三日の旅——すべてが胸の中の静寂へと変わっていた。"],
            ["END_GOOD_05"]  = ["  遠處，村民們向你奔來，歡呼聲響徹雲霄。",
                                "  In the distance, villagers rush toward you, their cheers filling the sky.",
                                "  遠くで村人たちがこちらへ駆けてくる。歓声が空いっぱいに響いた。"],
            ["END_GOOD_06"]  = ["  那位老婆婆也在人群中，對你露出感激的微笑。",
                                "  The old woman is there in the crowd, smiling at you with boundless gratitude.",
                                "  あの老婆も人群れの中にいて、感謝の笑みを浮かべてお前を見つめていた。"],
            ["END_GOOD_07"]  = ["  「我做到了。」",
                                "  \"I did it.\"",
                                "  「やった。」"],
            ["END_GOOD_08"]  = ["  這三個字，你等了三年。",
                                "  Three words. Three years in the making.",
                                "  その三文字を、お前は三年間待ち続けた。"],
            ["END_GOOD_WARRIOR"] = ["  有人問你，接下來要去哪裡。",
                                    "  Someone asks where you'll go next.",
                                    "  誰かが、これからどこへ行くのかと訊いた。"],
            ["END_GOOD_WARRIOR_2"] = ["  「繼續走吧，」你說，「世界還有更多地方需要守護。」",
                                      "  \"Keep going,\" you say. \"There are more places in this world that need protecting.\"",
                                      "  「歩き続けるよ」お前は言った。「この世界にはまだ、守るべき場所がある。」"],
            ["END_GOOD_MAGE"]   = ["  有人問你，那股強大的魔力是怎麼來的。",
                                   "  Someone asks where that immense power came from.",
                                   "  誰かが、あの強大な魔力はどこから来たのかと訊いた。"],
            ["END_GOOD_MAGE_2"] = ["  「也許...是來自你們的期待吧。」你微微一笑。",
                                   "  \"Maybe... it came from your belief in me.\" You smile faintly.",
                                   "  「おそらく……皆の期待から来たのでしょう。」お前は微かに笑った。"],
            ["END_GOOD_ASSASSIN"]  = ["  人群中，你沒有站在最前面，",
                                      "  In the crowd, you don't stand at the front.",
                                      "  人群れの中で、お前は最前列には立たない。"],
            ["END_GOOD_ASSASSIN_2"]= ["  但那個角落裡的微笑，是真實的。",
                                      "  But that quiet smile from the corner — it's real.",
                                      "  しかし、あの隅で浮かべた笑みは本物だった。"],
            ["END_GOOD_FUTURE"]    = ["  至於未來——", "  As for what comes next —", "  未来については——"],
            ["END_GOOD_FUTURE_2"]  = ["  那是另一個故事了。", "  that's another story.", "  それはまた別の話だ。"],
            ["END_GOOD_LABEL"]  = ["GOOD ENDING  ─  光明的彼岸", "GOOD ENDING  ─  Dawn of Light", "GOOD ENDING  ─  光の彼方"],

            // ── Ending: Good (Lonely) ───────────────────────────────────────
            ["END_LONELY_TITLE"] = ["好結局：孤獨的勝者", "Good Ending: The Lonely Victor", "グッドエンド：孤独な勝者"],
            ["END_LONE_01"] = ["  {0} 佇立在廢墟上，等待著什麼。",
                               "  {0} stands in the ruins, waiting for something.",
                               "  {0}は廃墟に立ち、何かを待っていた。"],
            ["END_LONE_02"] = ["  村民們向你奔來，歡呼聲響徹雲霄。",
                               "  Villagers rush toward you, cheers filling the sky.",
                               "  村人たちがこちらへ駆けてくる。歓声が空いっぱいに響く。"],
            ["END_LONE_03"] = ["  但你記得那條路上的哭聲，",
                               "  But you remember the cries back on that road.",
                               "  しかしお前はあの道での叫び声を覚えている。"],
            ["END_LONE_04"] = ["  記得你沒有停下腳步。",
                               "  You remember that you didn't stop.",
                               "  足を止めなかったことを覚えている。"],
            ["END_LONE_WARRIOR"]   = ["  戰士的信條是前進、前進、再前進，",
                                      "  A warrior's creed is to advance, advance, always advance.",
                                      "  戦士の信念は前進、前進、また前進。"],
            ["END_LONE_WARRIOR_2"] = ["  但此刻，你第一次懷疑那條信條是否完整。",
                                      "  But now, for the first time, you wonder if that creed is whole.",
                                      "  しかし今、初めてその信念が完全かどうかを疑っていた。"],
            ["END_LONE_MAGE"]   = ["  知識讓你強大，書讓你聰明，",
                                   "  Knowledge made you powerful, books made you wise,",
                                   "  知識がお前を強くし、書物がお前を賢くした。"],
            ["END_LONE_MAGE_2"] = ["  但有些課題，書上根本找不到。",
                                   "  but some lessons simply cannot be found in books.",
                                   "  しかし、書物には載っていない教訓がある。"],
            ["END_LONE_ASSASSIN"]  = ["  刺客的本能是不回頭，不留戀，",
                                      "  An assassin's instinct is to never look back, never linger.",
                                      "  暗殺者の本能は振り返らず、未練を持たないこと。"],
            ["END_LONE_ASSASSIN_2"]= ["  但今天，那種本能讓你感到一種難以名狀的刺痛。",
                                      "  But today, that instinct leaves a wordless sting.",
                                      "  しかし今日、その本能が言葉にならない痛みをもたらした。"],
            ["END_LONE_05"] = ["  世界得救了，這是事實。",
                               "  The world is saved — that much is true.",
                               "  世界は救われた——それは事実だ。"],
            ["END_LONE_06"] = ["  你一個人做到了——這也是事實。",
                               "  You did it alone — that is also true.",
                               "  お前一人でやり遂げた——それも事実だ。"],
            ["END_LONE_07"] = ["  在慶祝的人群中，你感到一種奇異的疏離。",
                               "  In the celebrating crowd, you feel a strange, hollow distance.",
                               "  お祝いの人群れの中で、お前は奇妙な疎外感を覚えていた。"],
            ["END_LONE_08"] = ["  「勝利是什麼味道？」",
                               "  \"What does victory taste like?\"",
                               "  「勝利とはどんな味がするのだろう？」"],
            ["END_LONE_09"] = ["  也許，等你找到答案，才算真的完成了這段旅程。",
                               "  Perhaps when you find that answer, the journey will be truly complete.",
                               "  その答えを見つけた時、初めてこの旅が本当に終わるのかもしれない。"],
            ["END_LONE_LABEL"]  = ["GOOD ENDING  ─  孤獨的勝者", "GOOD ENDING  ─  The Lonely Victor", "GOOD ENDING  ─  孤独な勝者"],

            // ── Ending: Grey ─────────────────────────────────────────────────
            ["END_GREY_TITLE"] = ["灰色結局：業火之中的行者", "Grey Ending: Walker Through the Flames", "グレーエンド：業火の中の旅人"],
            ["END_GREY_01"] = ["  魔王的黑暗消散了，但你的心底——",
                               "  The Demon King's darkness has faded — but deep in your heart —",
                               "  魔王の闇は消えた——しかし心の奥底には——"],
            ["END_GREY_02"] = ["  還留著一片灰燼。",
                               "  there remains a bed of ash.",
                               "  灰が残ったままだ。"],
            ["END_GREY_03"] = ["  {0} 沒有像英雄一樣歡呼，",
                               "  {0} doesn't cheer like a hero.",
                               "  {0}は英雄のように歓声を上げない。"],
            ["END_GREY_04"] = ["  也沒有因黑暗沉淪——只是靜靜地站著，",
                               "  Nor sinks into darkness — just stands quietly,",
                               "  かといって闇に沈むこともなく——ただ静かに立って、"],
            ["END_GREY_05"] = ["  望著遠方，某種說不清的東西壓在胸口。",
                               "  staring into the distance, something unnameable heavy on your chest.",
                               "  遠くを見つめ、名状しがたい何かが胸に重くのしかかっている。"],
            ["END_GREY_HELPED_1"] = ["  老婆婆從人群中走來，握住你的手。",
                                     "  The old woman comes forward from the crowd and takes your hand.",
                                     "  老婆が人群れから進み出て、お前の手を握った。"],
            ["END_GREY_HELPED_2"] = ["  「孩子，你還在這裡。這就夠了。」",
                                     "  \"Child, you're still here. That's enough.\"",
                                     "  「坊や、まだここにいる。それで十分だ。」"],
            ["END_GREY_NOTHELPED_1"] = ["  老祭司靜靜走來，沒有稱讚，也沒有責備。",
                                        "  The old priest walks over quietly — no praise, no blame.",
                                        "  老祭司が静かに近づいてくる——称賛も責めもなく。"],
            ["END_GREY_NOTHELPED_2"] = ["  「你回來了。」他說，僅此而已。",
                                        "  \"You returned,\" he says. Nothing more.",
                                        "  「戻ってきたか。」彼はそれだけ言った。"],
            ["END_GREY_WARRIOR"]    = ["  戰士的路，原以為只是勝與敗，",
                                       "  You thought a warrior's path was simply win or lose.",
                                       "  戦士の道は勝ち負けだけだと思っていた。"],
            ["END_GREY_WARRIOR_2"]  = ["  卻不料，中間還有寬闊的灰色地帶。",
                                       "  But between them lies a vast, gray expanse.",
                                       "  しかし、その間には広大なグレーの地帯があった。"],
            ["END_GREY_MAGE"]       = ["  魔法的真理，從不是非黑即白，",
                                       "  The truth of magic was never black and white.",
                                       "  魔法の真理は決して白か黒かではなかった。"],
            ["END_GREY_MAGE_2"]     = ["  你終於明白了，只是代價有點大。",
                                       "  You understand that now. The price was just higher than expected.",
                                       "  ようやく理解した。ただ、代償は少し大きすぎた。"],
            ["END_GREY_ASSASSIN"]   = ["  生活在陰影中的人，最了解灰色的味道，",
                                       "  Those who live in shadow know the taste of gray best.",
                                       "  影に生きる者は、灰色の味を最もよく知っている。"],
            ["END_GREY_ASSASSIN_2"] = ["  但這次嚐到的，比任何時候都深。",
                                       "  But this time, the taste cuts deeper than ever.",
                                       "  しかし今回はどんな時よりも深く、その味が刻まれた。"],
            ["END_GREY_06"] = ["  你不確定自己算是英雄還是罪人，",
                               "  You're not sure if you're a hero or a sinner.",
                               "  自分が英雄なのか罪人なのか、お前にはわからない。"],
            ["END_GREY_07"] = ["  也許，答案會在往後的歲月中慢慢浮現。",
                               "  Perhaps the answer will surface slowly in the years to come.",
                               "  おそらく、その答えはこれからの年月の中でゆっくりと浮かんでくるだろう。"],
            ["END_GREY_08"] = ["  或者，永遠不會。",
                               "  Or perhaps it never will.",
                               "  あるいは、永遠に浮かんでこないかもしれない。"],
            ["END_GREY_LABEL"] = ["GREY ENDING  ─  業火之中的行者", "GREY ENDING  ─  Walker Through the Flames", "GREY ENDING  ─  業火の中の旅人"],

            // ── Ending: Bad ─────────────────────────────────────────────────
            ["END_BAD_TITLE"]  = ["壞結局：黑暗的繼承者", "Bad Ending: Heir to Darkness", "バッドエンド：闇の後継者"],
            ["END_BAD_01"] = ["  魔王倒下了，但你感到某種陌生的空洞。",
                              "  The Demon King has fallen, but you feel a strange, hollow emptiness.",
                              "  魔王は倒れた。しかしお前は奇妙な空虚さを感じていた。"],
            ["END_BAD_02"] = ["  那些吸收的黑暗、那些交易換來的力量——",
                              "  The darkness you absorbed, the power you bargained for —",
                              "  吸収した闇、取引で得た力——"],
            ["END_BAD_03"] = ["  它們不知何時已深深紮根在你的靈魂之中。",
                              "  they have taken root deep in your soul without you noticing.",
                              "  それらはいつの間にか、お前の魂の奥深くに根を張っていた。"],
            ["END_BAD_04"] = ["  {0} 緩緩舉起雙手，",
                              "  {0} slowly raises both hands,",
                              "  {0}はゆっくりと両手を持ち上げた。"],
            ["END_BAD_05"] = ["  手掌上蔓延著黑暗的紋路，和魔王死前的模樣如出一轍。",
                              "  Dark veins spreading across the palms — identical to the Demon King's final form.",
                              "  手のひらに広がる暗黒の紋様——魔王が死ぬ前の姿と寸分違わぬ。"],
            ["END_BAD_06"] = ["  身後，村民們看見了你的變化，紛紛後退。",
                              "  Behind you, the villagers see your transformation and recoil.",
                              "  後方で、村人たちはお前の変化を見て一斉に後退した。"],
            ["END_BAD_07"] = ["  「怪物...那是怪物！」",
                              "  \"A monster... that thing is a monster!\"",
                              "  「化け物……あれは化け物だ！」"],
            ["END_BAD_WARRIOR"]   = ["  盔甲之下，那份曾作為戰士的驕傲，",
                                     "  Beneath the armor, the pride you once held as a warrior",
                                     "  鎧の下、戦士として誇りに思っていたものが"],
            ["END_BAD_WARRIOR_2"] = ["  正在慢慢碎裂。",
                                     "  is slowly cracking apart.",
                                     "  ゆっくりと砕け散っていく。"],
            ["END_BAD_MAGE"]   = ["  魔力的流動已不再純淨，",
                                  "  The flow of magic within you is no longer pure.",
                                  "  魔力の流れはもはや純粋ではない。"],
            ["END_BAD_MAGE_2"] = ["  你甚至分不清那是你的意志，還是黑暗的呼喚。",
                                  "  You can no longer tell if it's your will or the darkness calling.",
                                  "  それがお前の意志なのか、闇の呼び声なのか、もはや区別できない。"],
            ["END_BAD_ASSASSIN"]   = ["  陰影一直是你的盟友，",
                                      "  Shadows have always been your ally.",
                                      "  影はずっとお前の味方だった。"],
            ["END_BAD_ASSASSIN_2"] = ["  只是現在，連陰影都開始感到陌生。",
                                      "  But now, even the shadows feel unfamiliar.",
                                      "  しかし今は、その影さえも見知らぬものに感じる。"],
            ["END_BAD_08"] = ["  打倒魔王的你，已經成為了新的黑暗。",
                              "  You who defeated the Demon King — have become the new darkness.",
                              "  魔王を倒したお前が、新たな闇となった。"],
            ["END_BAD_09"] = ["  也許某天，又會有一個勇者被老祭司叫醒，",
                              "  Perhaps one day, another hero will be awakened by an old priest,",
                              "  いつか、また別の勇者が老祭司に起こされ、"],
            ["END_BAD_10"] = ["  被派來尋找你。",
                              "  and sent to find you.",
                              "  お前を探しに派遣されるだろう。"],
            ["END_BAD_LABEL"]  = ["BAD ENDING  ─  黑暗的繼承者", "BAD ENDING  ─  Heir to Darkness", "BAD ENDING  ─  闇の後継者"],

            // ── Ending: Worst ────────────────────────────────────────────────
            ["END_WORST_TITLE"] = ["最壞結局：魔王轉世", "Worst Ending: The Demon Reborn", "ワーストエンド：魔王転生"],
            ["END_WORST_01"] = ["  夜陌魯斯死了。",
                                "  Yamatolusu is dead.",
                                "  夜陌魯斯は死んだ。"],
            ["END_WORST_02"] = ["  但世界並不因此感到安全。",
                                "  But the world does not feel safe.",
                                "  しかし世界は安全を感じていない。"],
            ["END_WORST_03"] = ["  {0} 緩緩轉身，黑暗的紋路已爬滿全身，",
                                "  {0} slowly turns. Dark veins cover every inch of the body.",
                                "  {0}はゆっくりと振り向く。暗黒の紋様が全身を覆っている。"],
            ["END_WORST_04"] = ["  那雙眼睛裡，燃燒著和魔王一模一樣的光。",
                                "  In those eyes burns the exact same light as the Demon King's.",
                                "  その瞳には、魔王と全く同じ光が燃えている。"],
            ["END_WORST_05"] = ["  遠處，逃難的士兵對同伴低語：",
                                "  In the distance, fleeing soldiers whisper to each other:",
                                "  遠くで、逃げる兵士たちが互いに囁き合っている："],
            ["END_WORST_06"] = ["  「魔王死了...但那個人...」",
                                "  \"The Demon King is dead... but that person...\"",
                                "  「魔王は死んだ……でもあの人は……」"],
            ["END_WORST_07"] = ["  「那個人比魔王更可怕。」",
                                "  \"That person is more terrifying than the Demon King.\"",
                                "  「あの人は魔王より恐ろしい。」"],
            ["END_WORST_WARRIOR"]   = ["  曾被稱為無畏戰士的名字，",
                                       "  The name once hailed as a fearless warrior",
                                       "  かつて無敵の戦士と称えられた名前は、"],
            ["END_WORST_WARRIOR_2"] = ["  如今成了孩子們夜間最怕聽到的詞語。",
                                       "  has become the word children fear most in the dark.",
                                       "  今では子どもたちが夜最も恐れる言葉となった。"],
            ["END_WORST_MAGE"]   = ["  曾被稱為智慧法師的那雙手，",
                                    "  The hands once called those of a wise mage",
                                    "  かつて賢明な魔法使いの手と呼ばれたその手は、"],
            ["END_WORST_MAGE_2"] = ["  如今只知道如何施展毀滅的魔法。",
                                    "  now know only how to cast magic of destruction.",
                                    "  今では破壊の魔法しか知らない。"],
            ["END_WORST_ASSASSIN"]   = ["  曾在陰影中守護的那個身影，",
                                        "  The figure that once protected from the shadows",
                                        "  かつて影から守護していたあの姿は、"],
            ["END_WORST_ASSASSIN_2"] = ["  如今成了陰影本身。",
                                        "  has become the shadow itself.",
                                        "  今では影そのものとなった。"],
            ["END_WORST_08"] = ["  黑暗的輪迴並沒有終結——",
                                "  The cycle of darkness has not ended —",
                                "  闇の輪廻は終わっていない——"],
            ["END_WORST_09"] = ["  只是換了一個人來背負它。",
                                "  it has merely found a new person to carry it.",
                                "  ただ、それを背負う人間が変わっただけだ。"],
            ["END_WORST_10"] = ["  你覺得，這一次，還有人能阻止它嗎？",
                                "  Do you think — this time — there is anyone who can stop it?",
                                "  今度こそ、それを止められる者はいると思うか？"],
            ["END_WORST_LABEL"] = ["WORST ENDING  ─  魔王轉世", "WORST ENDING  ─  The Demon Reborn", "WORST ENDING  ─  魔王転生"],

            // ── Ending: Hidden Berserk ──────────────────────────────────────
            ["END_HBSRK_TITLE"] = ["★ 隱藏結局：暴走聖者 ★", "★ Hidden Ending: The Berserk Saint ★", "★ 隠しエンド：暴走の聖者 ★"],
            ["END_HBSRK_01"] = ["  在暴走的狂風暴雨之中，你打倒了魔王。",
                                "  In the storm of your berserk fury, you brought the Demon King down.",
                                "  暴走の嵐の中、お前は魔王を打ち倒した。"],
            ["END_HBSRK_02"] = ["  那股失控的力量——它一直都在你的掌控之中。",
                                "  That 'uncontrollable' power — it was always within your control.",
                                "  あの「制御不能」な力——それは最初からお前の掌の中にあった。"],
            ["END_HBSRK_03"] = ["  {0} 緩緩從暴走狀態中甦醒，",
                                "  {0} slowly comes down from the berserk state,",
                                "  {0}はゆっくりと暴走状態から覚め、"],
            ["END_HBSRK_04"] = ["  卻比任何時候都更加清醒、更加平靜。",
                                "  more clear-headed and calm than at any other moment.",
                                "  どんな時よりも澄み切って、穏やかだった。"],
            ["END_HBSRK_05"] = ["  「我明白了。不是壓制憤怒，」",
                                "  \"I understand now. It's not about suppressing the rage —\"",
                                "  「わかった。怒りを抑えることではない——」"],
            ["END_HBSRK_06"] = ["  「而是——與它共存。」",
                                "  \"— it's about coexisting with it.\"",
                                "  「——それと共に生きることだ。」"],
            ["END_HBSRK_WARRIOR"]   = ["  從今以後，那把劍所到之處，",
                                       "  From this day forward, wherever that sword travels,",
                                       "  今日からその剣が向かう場所では、"],
            ["END_HBSRK_WARRIOR_2"] = ["  怒火不再是破壞，而是一道守護的屏障。",
                                       "  rage is no longer destruction — it is a shield of protection.",
                                       "  怒りはもはや破壊ではなく、守護の盾となる。"],
            ["END_HBSRK_MAGE"]   = ["  從今以後，你的魔法中融入了怒與靜，",
                                    "  From this day forward, your magic blends fury and stillness,",
                                    "  今日から、お前の魔法には怒りと静寂が融け合い、"],
            ["END_HBSRK_MAGE_2"] = ["  那是這個世界前所未見的力量形態。",
                                    "  a form of power this world has never seen before.",
                                    "  この世界が一度も見たことのない力の形となる。"],
            ["END_HBSRK_ASSASSIN"]   = ["  從今以後，你在黑暗中行動，",
                                        "  From this day forward, you move through darkness,",
                                        "  今日から、お前は闇の中を動き、"],
            ["END_HBSRK_ASSASSIN_2"] = ["  但那團怒火，成了你永不熄滅的方向感。",
                                        "  but that burning rage becomes your compass — never extinguished.",
                                        "  しかしあの怒りの炎が、永遠に消えない羅針盤となる。"],
            ["END_HBSRK_07"] = ["  世界還有很多裂縫未被縫合，",
                                "  The world still has many wounds left to heal,",
                                "  世界にはまだ多くの傷が癒えていない。"],
            ["END_HBSRK_08"] = ["  但那都是明天的事了。",
                                "  but that is a matter for tomorrow.",
                                "  でもそれは明日のことだ。"],
            ["END_HBSRK_09"] = ["  此刻，你只需要站在這裡，呼吸。",
                                "  For now, you only need to stand here and breathe.",
                                "  今は、ただここに立って、息をするだけでいい。"],
            ["END_HBSRK_LABEL"]   = ["SECRET ENDING ★  ─  暴走聖者", "SECRET ENDING ★  ─  The Berserk Saint", "SECRET ENDING ★  ─  暴走の聖者"],
            ["END_HBSRK_CONGRATS"]= ["🎊 恭喜你發現了隱藏結局！", "🎊 Congratulations! You found the hidden ending!", "🎊 おめでとう！隠しエンドを発見！"],

            // ── Ending: Hidden Pure ─────────────────────────────────────────
            ["END_HPURE_TITLE"] = ["✦ 隱藏結局：純淨之道 ✦", "✦ Hidden Ending: The Pure Path ✦", "✦ 隠しエンド：純粋の道 ✦"],
            ["END_HPURE_01"] = ["  純白的光從天空傾瀉而下——",
                                "  Pure white light pours down from the sky —",
                                "  純白の光が天から降り注ぐ——"],
            ["END_HPURE_02"] = ["  不是魔法，不是憤怒，而是你自己的光。",
                                "  not magic, not rage — your own light.",
                                "  魔法でも怒りでもない、お前自身の光だ。"],
            ["END_HPURE_03"] = ["  {0} 站在魔王消散的地方，雙手沒有顫抖。",
                                "  {0} stands where the Demon King dissolved. Your hands do not tremble.",
                                "  {0}は魔王が消えた場所に立っている。両手は震えていない。"],
            ["END_HPURE_04"] = ["  整段旅程，你從未讓憤怒佔據你，",
                                "  Throughout the entire journey, you never let rage consume you,",
                                "  旅の全てを通じて、お前は怒りに支配されることなく、"],
            ["END_HPURE_05"] = ["  從未以黑暗換取捷徑，",
                                "  never traded in darkness for a shortcut,",
                                "  闇で近道を買うことなく、"],
            ["END_HPURE_06"] = ["  你甚至在最疲憊的時候，回頭救了那位老婆婆。",
                                "  and even at your most exhausted, you turned back to save that old woman.",
                                "  最も疲弊していた時でさえ、振り返ってあの老婆を救った。"],
            ["END_HPURE_07"] = ["  老祭司看著你回來，沉默良久後，緩緩跪下。",
                                "  The old priest watches you return. After a long silence, he slowly kneels.",
                                "  老祭司がお前の帰りを見守る。長い沈黙の後、ゆっくりと膝をついた。"],
            ["END_HPURE_08"] = ["  「我見過無數勇者，」他說，聲音顫抖，",
                                "  \"I have seen countless heroes,\" he says, his voice trembling,",
                                "  「多くの勇者を見てきた」彼は言った、声を震わせながら、"],
            ["END_HPURE_09"] = ["  「但只有你——是真正意義上的英雄。」",
                                "  \"but you — you alone are a true hero in every sense of the word.\"",
                                "  「しかしお前だけが——本当の意味での英雄だ。」"],
            ["END_HPURE_WARRIOR"]   = ["  人們傳說，那名戰士的劍從未沾染過不義之血。",
                                       "  People would say: that warrior's blade never tasted unjust blood.",
                                       "  人々は語り継ぐ——あの戦士の剣は、不義の血を一度も染めなかった。"],
            ["END_HPURE_MAGE"]      = ["  人們傳說，那名法師的魔法之中，帶著光一般的溫度。",
                                       "  People would say: that mage's magic carried a warmth like light itself.",
                                       "  人々は語り継ぐ——あの魔法使いの魔法には、光のような温もりがあった。"],
            ["END_HPURE_ASSASSIN"]  = ["  人們傳說，那名刺客從陰影中走出，卻把陽光帶回了世界。",
                                       "  People would say: that assassin stepped out of shadow and brought the sun back with them.",
                                       "  人々は語り継ぐ——あの暗殺者は影から歩み出て、太陽を世界に連れ戻した。"],
            ["END_HPURE_10"] = ["  天空的顏色，比昨天更藍了一些。",
                                "  The sky is a shade bluer than yesterday.",
                                "  空の色は昨日より少し青くなった。"],
            ["END_HPURE_11"] = ["  關於明天，你心裡還沒有答案。",
                                "  As for tomorrow — you don't have answers yet.",
                                "  明日については——まだ答えがない。"],
            ["END_HPURE_12"] = ["  但這一刻，只有平靜。",
                                "  But in this moment, there is only peace.",
                                "  しかしこの瞬間、ただ静寂だけがある。"],
            ["END_HPURE_LABEL"]   = ["HIDDEN ENDING ✦  ─  純淨之道", "HIDDEN ENDING ✦  ─  The Pure Path", "HIDDEN ENDING ✦  ─  純粋の道"],
            ["END_HPURE_CONGRATS"]= ["✦ 恭喜！你以最純粹的方式完成了整段旅程！", "✦ Congratulations! You completed the journey in the purest way!", "✦ おめでとう！最も純粋な方法で旅を完走！"],

            // ── Game Over ──────────────────────────────────────────────────
            ["GAMEOVER_01"] = ["  {0} 倒在了黑暗之中...",
                               "  {0} has fallen into the darkness...",
                               "  {0}が闇の中に倒れた…"],
            ["GAMEOVER_02"] = ["  黑暗漫過大地，吞噬了一切光明。",
                               "  Darkness floods the land, consuming all light.",
                               "  闇が大地を覆い、全ての光を呑み込んだ。"],
            ["GAMEOVER_03"] = ["  世界，失去了最後的希望。",
                               "  The world has lost its last hope.",
                               "  世界は最後の希望を失った。"],
            ["GAMEOVER_HINT"] = ["  按 [R] 重新開始，按其他鍵退出...",
                                 "  Press [R] to restart, any other key to exit...",
                                 "  [R]でリスタート、他のキーで終了…"],

            // ── Credits ────────────────────────────────────────────────────
            ["CREDITS_TITLE"]  = ["旅 程 終 結", "JOURNEY'S  END", "旅の終わり"],
            ["CREDITS_THANKS"] = ["  感謝遊玩《暴走：黑暗年代記》！", "  Thank you for playing RAGE: Chronicles of Darkness!", "  「暴走：黑暗年代記」をプレイしてくれてありがとう！"],
            ["CREDITS_STATS"]  = ["  ─── 本局統計 ───────────────────────────", "  ─── RUN STATS ─────────────────────────", "  ─── 今回の記録 ──────────────────────"],
            ["CREDITS_NAME"]   = ["  角色名稱", "  Name", "  名前"],
            ["CREDITS_LEVEL"]  = ["  最終等級", "  Final Level", "  最終レベル"],
            ["CREDITS_HP"]     = ["  最終 HP", "  Final HP", "  最終HP"],
            ["CREDITS_CORRUPT"]= ["  腐化值", "  Corruption", "  腐敗値"],
            ["CREDITS_BERSERK"]= ["  暴走次數", "  Berserk Count", "  暴走回数"],
            ["CREDITS_HELPED"] = ["  幫助村民", "  Helped Villager", "  村人を助けた"],
            ["CREDITS_DARK"]   = ["  接受黑暗", "  Accepted Dark", "  闇を受け入れた"],
            ["CREDITS_YES"]    = ["是", "Yes", "はい"],
            ["CREDITS_NO"]     = ["否", "No", "いいえ"],

            // ── Help Screen ────────────────────────────────────────────────
            ["HELP_TITLE"]       = ["遊 玩 說 明", "HOW  TO  PLAY", "ゲーム説明"],
            ["HELP_BASICS"]      = ["  ◆ 基本玩法", "  ◆ Basics", "  ◆ 基本操作"],
            ["HELP_BASICS_1"]    = ["    每回合選擇行動：攻擊 / 技能 / 防禦", "    Each turn choose: Attack / Skill / Defend", "    毎ターン選択：攻撃 / スキル / 防御"],
            ["HELP_BASICS_2"]    = ["    擊敗敵人獲得 EXP，升等後屬性提升", "    Defeat enemies for EXP and level up", "    敵を倒しEXP獲得、レベルアップで能力上昇"],
            ["HELP_BERSERK"]     = ["  ◆ 暴走系統", "  ◆ Berserk System", "  ◆ 暴走システム"],
            ["HELP_BERSERK_1"]   = ["    攻擊和受傷都會累積怒氣（0-100）", "    Attacking and taking damage builds rage (0-100)", "    攻撃・被ダメで怒気蓄積（0-100）"],
            ["HELP_BERSERK_2"]   = ["    怒氣滿了自動觸發【暴走狀態】（4回合）", "    Full rage auto-triggers [BERSERK] (4 turns)", "    怒気MAX→【暴走状態】自動発動（4ターン）"],
            ["HELP_BERSERK_3"]   = ["    暴走中：攻擊力 ×1.5，但每次攻擊有 20% 反噬", "    Berserk: ATK ×1.5, but 20% backfire chance", "    暴走中：ATK×1.5、ただし20%で自傷"],
            ["HELP_SKILLS"]      = ["  ◆ 技能系統", "  ◆ Skill System", "  ◆ スキルシステム"],
            ["HELP_SKILLS_1"]    = ["    火球術  ── 消耗 MP，高傷害 + 燃燒機率", "    Fireball   ── MP cost, high damage + burn", "    火球術  ── MP消費、高ダメ＋燃焼"],
            ["HELP_SKILLS_2"]    = ["    治癒術  ── 消耗 MP，恢復 HP", "    Heal       ── MP cost, restores HP", "    治癒術  ── MP消費、HP回復"],
            ["HELP_SKILLS_3"]    = ["    盾擊    ── 消耗 MP，傷害 + 眩暈機率", "    Shield Bash ── MP cost, damage + stun chance", "    盾擊    ── MP消費、ダメ＋眩暈"],
            ["HELP_SKILLS_4"]    = ["    暴走衝擊 ── 消耗 40 怒氣，超高傷害 + 暴擊", "    Berserk Smash ── 40 rage, massive damage + crit", "    暴走スマッシュ ── 怒気40、超大ダメ＋クリティカル"],
            ["HELP_ENDINGS"]     = ["  ◆ 結局（共 7 種，職業與選擇皆會影響）", "  ◆ Endings (7 total — class and choices matter)", "  ◆ エンディング（全7種、クラスと選択が影響）"],
            ["HELP_ENDINGS_HINT"]= ["    結局的走向... 由你的旅程決定。", "    The path of each ending... is determined by your journey.", "    各エンディングへの道……それはお前の旅が決める。"],

            // ── Save / Load ────────────────────────────────────────────────
            ["SAVE_AUTO"]       = ["  [遊戲已自動儲存]", "  [Game auto-saved]", "  [自動セーブ完了]"],
            ["LOAD_SUCCESS"]    = ["  ✓ 讀取成功！繼續 {0} 的旅程。", "  ✓ Loaded! Continuing {0}'s journey.", "  ✓ ロード成功！{0}の旅を続ける。"],
            ["LOAD_CHAPTER"]    = ["  ▶ 從第 {0} 章繼續", "  ▶ Resuming from Chapter {0}", "  ▶ 第{0}章から再開"],
            ["LOAD_FAIL"]       = ["  ✗ 找不到存檔！", "  ✗ No save file found!", "  ✗ セーブデータが見つからない！"],
            ["LOAD_CORRUPT"]    = ["  ✗ 存檔損壞，開始新遊戲。", "  ✗ Save corrupted, starting new game.", "  ✗ セーブデータ破損、新しいゲームを開始。"],

            // ── Common Prompts ──────────────────────────────────────────────
            ["PRESS_ANY_KEY"]      = ["[ 按任意鍵繼續... ]", "[ Press any key to continue... ]", "[ 何かキーを押してください… ]"],
            ["PRESS_ANY_KEY_MENU"] = ["[ 按任意鍵返回主選單 ]", "[ Press any key to return to main menu ]", "[ 何かキーを押してメインメニューへ ]"],
            ["INPUT_ERROR"]        = ["  ✗ 請輸入 {0} 到 {1} 之間的數字", "  ✗ Please enter a number between {0} and {1}", "  ✗ {0}から{1}の間の数字を入力してください"],

            // ── Equipment & Story Bonus Lines ─────────────────────────────
            ["STORY_HP_BONUS"]  = ["  ✦ 獲得老婆婆的祝福（最大 HP +15）",
                                   "  ✦ Received the old woman's blessing (Max HP +15)",
                                   "  ✦ 老婆の祝福を受けた（最大HP+15）"],
            ["STORY_EQUIP_DARK_MSG"] = ["  ✦ 黑暗能量注入聖劍，你感覺它在呼應你體內的腐化。",
                                         "  ✦ Dark energy flows into the blade, resonating with your corruption.",
                                         "  ✦ 暗黒のエネルギーが聖剣に宿り、体内の腐敗と共鳴している。"],
            ["STORY_EQUIP_HOLY_MSG"] = ["  ✦ 聖劍的力量在你手中閃耀，彷彿認可了你的意志。",
                                         "  ✦ The blade gleams in your hand, as if acknowledging your will.",
                                         "  ✦ 聖剣の力がお前の手の中で輝き、意志を認めるかのようだ。"],
            ["STORY_DEAL_BONUS_MSG"] = ["  ✦ 所有屬性大幅提升，但腐化值已達警戒線",
                                         "  ✦ All stats greatly increased — but corruption is critical",
                                         "  ✦ 全ステータス大幅上昇——しかし腐敗値が警戒ラインに達した"],
            ["STORY_ATK_BONUS"]      = ["  ✦ ATK +6，但腐化值大幅上升",
                                         "  ✦ ATK +6, but corruption greatly increased",
                                         "  ✦ ATK+6、しかし腐敗値が大幅上昇"],
        };
    }
}
